-- FOR UPDATE - TRAVA A REQUISIÇÃO - PESSIMISTIC LOCKING

-- BEGIN;
--   SELECT * FROM bank_accounts WHERE user_id = 1 FOR UPDATE;
--   UPDATE bank_accounts SET balance = balance - 200.00 WHERE user_id = 1;
--   COMMIT;

-- select * from bank_accounts;

-- VERSIONING - VERSION 1
-- UPDATE products SET price = 100.00 WHERE id = 1, version = version + 1;

-- ISOLATION LEVELS
-- SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

-- SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

-- SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

-- SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

-- SET TRANSACTION ISOLATION LEVEL READ COMMITTED SNAPSHOT;

-- SET TRANSACTION ISOLATION LEVEL REPEATABLE READ SNAPSHOT;